In [8]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

The MNIST database is a large dataset of handwritten digits, containing 70,000 images of handwritten digits (from 0 to 9). Each image is a grayscale image of size 28x28 pixels, which has been flattened into a 784-dimensional vector (28*28 = 784). The target labels are the digits corresponding to each image, ranging from 0 to 9. There are 10 unique classes.

In [2]:
X, y = fetch_openml("mnist_784", version= 1, return_X_y= True)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [21]:
print(X.shape)

(70000, 784)


In [6]:
X.head()

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

   pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
1      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
2      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
3      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   
4      0.0  ...       0.0       0.0       0.0       0.0       0.0       0.0   

   pixel781  pixel782  pixel783  pixel784  
0       0.0       0.0       0.0       0.0  
1       0.0       0.0       0.0       0.0  
2       0.0       0.0       0.0       0.0  
3       0.0       0.0       0.0       0.0  
4       0.0       0.0       0.0       0.0  

[5 rows x 784 columns]

In [11]:
print(np.min(X))
print(np.max(X))

0.0
255.0


In [12]:
X_train, X_test, y_train, y_test = train_test_split(X/255., y, test_size= 0.20, random_state=1)

In [13]:
perceptron = Perceptron(random_state= 1, max_iter= 50, tol=0.005)

In [14]:
perceptron.fit(X_train,y_train)

Perceptron(max_iter=50, random_state=1, tol=0.005)

In [15]:
yhat_train_perceptron = perceptron.predict(X_train)

In [16]:
yhat_test_perceptron = perceptron.predict(X_test)

In [17]:
print("Perceptron: Accuracy for training is %.2f" % (accuracy_score(y_train, yhat_train_perceptron)))

Perceptron: Accuracy for training is 0.90


In [18]:
print("Perceptron: Accuracy for testing is %.2f" % (accuracy_score(y_test, yhat_test_perceptron)))

Perceptron: Accuracy for testing is 0.88


In [ ]:
# Multi layer Perceptron

In [22]:
from sklearn.datasets import fetch_openml
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [23]:
X,y = fetch_openml('mnist_784', version= 1, return_X_y=True)

/usr/local/lib/python3.10/dist-packages/sklearn/datasets/_openml.py:968: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [24]:
X_train, X_test, y_train, y_test = train_test_split(X/255., y, test_size=0.20, random_state=1)

In [25]:
mlp = MLPClassifier (solver= "sgd", max_iter= 20, verbose= True, random_state= 1, learning_rate_init= 0.1, hidden_layer_sizes= (784, 100, 2))

In [26]:
mlp.fit( X_train, y_train)

Iteration 1, loss = 0.78419346
Iteration 2, loss = 0.40267290
Iteration 3, loss = 0.35031849
Iteration 4, loss = 0.20264795
Iteration 5, loss = 0.16538864
Iteration 6, loss = 0.13211615
Iteration 7, loss = 0.11156361
Iteration 8, loss = 0.09866746
Iteration 9, loss = 0.08842026
Iteration 10, loss = 0.08179945
Iteration 11, loss = 0.07511844
Iteration 12, loss = 0.05712572
Iteration 13, loss = 0.07087609
Iteration 14, loss = 0.06055471
Iteration 15, loss = 0.06877037
Iteration 16, loss = 0.05673940
Iteration 17, loss = 0.04027069
Iteration 18, loss = 0.04337515
Iteration 19, loss = 0.04764349
Iteration 20, loss = 0.05438006


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (20) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(784, 100, 2), learning_rate_init=0.1,
              max_iter=20, random_state=1, solver='sgd', verbose=True)

In [30]:
yhat_train_mlp = mlp.predict(X_train)

In [32]:
yhat_test_mlp = mlp.predict(X_test)

In [33]:
print("Multylayer perceptron accuracy for training set is %.2f" % (accuracy_score(y_train, yhat_train_mlp)))

Multylayer perceptron accuracy for training set is 0.99


In [34]:
print("Multylayer perceptron accuracy for test set is %.2f" % (accuracy_score(y_test, yhat_test_mlp)))

Multylayer perceptron accuracy for test set is 0.97


We notice a higher prediction accuracy with a multilayer perceptron.

In [ ]:
# NN for Regression

In [35]:
import urllib.request
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor

The Yacht Hydrodynamics dataset can be used for regression analysis. The goal is to predict the hydrodynamic performance of sailing yachts based on their design parameters. Specifically, we aim to predict the residuary resistance of a sailing yacht using various physical attributes of the yacht. The target variable is the residuary resistance per unit weight of displacement (RR), which needs to be predicted. It is present in the 7th column. Dataset has no headers.

In [36]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00243/yacht_hydrodynamics.data"

In [37]:
raw_data = urllib.request.urlopen(url)

In [38]:
dataset = np.loadtxt(raw_data)

In [39]:
dataset

array([[-2.3  ,  0.568,  4.78 , ...,  3.17 ,  0.125,  0.11 ],
       [-2.3  ,  0.568,  4.78 , ...,  3.17 ,  0.15 ,  0.27 ],
       [-2.3  ,  0.568,  4.78 , ...,  3.17 ,  0.175,  0.47 ],
       ...,
       [-2.3  ,  0.6  ,  4.34 , ...,  2.73 ,  0.4  , 19.59 ],
       [-2.3  ,  0.6  ,  4.34 , ...,  2.73 ,  0.425, 30.48 ],
       [-2.3  ,  0.6  ,  4.34 , ...,  2.73 ,  0.45 , 46.66 ]])

In [40]:
print(dataset.shape)

(308, 7)


In [41]:
data_scale = StandardScaler().fit_transform(dataset)

In [42]:
X_train, X_test, y_train, y_test = train_test_split (data_scale[: , 0:6], data_scale[:, 6], train_size= 0.25, random_state=1)

In [43]:
reg = MLPRegressor (hidden_layer_sizes= (3, 5), random_state=1). fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [44]:
prediction_result = reg.predict(X_test[2:3, :])

In [45]:
print(prediction_result)

[0.31985505]


In [48]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, reg.predict(X_test))

In [49]:
print(mse)

0.8604220710180743


In [50]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, reg.predict(X_test))
print(mae)

0.679058537850594


In [ ]:
# NN for Classification

In [15]:
import sklearn
import urllib.request
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier


In [16]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00236/seeds_dataset.txt"

Here, the goal is to classify seeds from three different varieties of wheat based on various geometric properties of their kernels.

In [17]:
raw_data = urllib.request.urlopen(url)

In [18]:
dataset = np.loadtxt(raw_data)

In [19]:
dataset

array([[15.26  , 14.84  ,  0.871 , ...,  2.221 ,  5.22  ,  1.    ],
       [14.88  , 14.57  ,  0.8811, ...,  1.018 ,  4.956 ,  1.    ],
       [14.29  , 14.09  ,  0.905 , ...,  2.699 ,  4.825 ,  1.    ],
       ...,
       [13.2   , 13.66  ,  0.8883, ...,  8.315 ,  5.056 ,  3.    ],
       [11.84  , 13.21  ,  0.8521, ...,  3.598 ,  5.044 ,  3.    ],
       [12.3   , 13.34  ,  0.8684, ...,  5.637 ,  5.063 ,  3.    ]])

In [20]:
print(dataset.shape)

(210, 8)


In [21]:
X = dataset[:, 0:7]
y = dataset[:, 7]

In [22]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [24]:
clf = MLPClassifier(solver='sgd', alpha=1e-5, hidden_layer_sizes=(5, 3), random_state=1)

In [25]:
clf.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 3), random_state=1,
              solver='sgd')

In [30]:
print("Train score:", clf.score(X_train, y_train))

Train score: 0.3503184713375796


In [26]:
score = clf.score(X_test, y_test)
print("Test score:", score)

Test score: 0.2830188679245283


In [27]:
print(clf.predict_proba(X_test[2:3, :]))

[[0.260604   0.43710656 0.30228943]]


In [28]:
print(clf.predict(X_test[2:3, :]))

[2.]
